#pragma once

#define IDR_CONTROL_FG_LOGO_BGRA 101
#define CONTROL_FG_LOGO_WIDTH 310
#define CONTROL_FG_LOGO_HEIGHT 50
#define CONTROL_FG_LOGO_BYTES (CONTROL_FG_LOGO_WIDTH * CONTROL_FG_LOGO_HEIGHT * 4)
